### ISSUE TITLE
Plugin stopped working after upgrading to storybook v7

### ISSUE THREAD

**Issue by SpaNb4** [happo/happo-plugin-storybook#102]
After a first look at the source code, it seems that something is wrong with the `resolveBuildCommandParts` function. 

CI logs:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/build-storybook - Not found
npm ERR! 404 
npm ERR! 404  'build-storybook@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /github/home/.npm/_logs/2023-12-21T17_13_55_076Z-debug-0.log
✗
Error: Failed to build static storybook package
    at ChildProcess.<anonymous> (/__w/vtx-ui-react-component-library/vtx-ui-react-component-library/node_modules/happo-plugin-storybook/index.js:85:16)
    at ChildProcess.emit (node:events:517:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:[29](https://github.com/vertexinc/vtx-ui-react-component-library/actions/runs/7291127463/job/19869429680?pr=1090#step:12:30)2:12)

/__w/vtx-ui-react-component-library/vtx-ui-react-component-library/node_modules/happo-plugin-storybook/index.js:85
        reject(new Error('Failed to build static storybook package'));
               ^
Error: Failed to build static storybook package
    at ChildProcess.<anonymous> (/__w/vtx-ui-react-component-library/vtx-ui-react-component-library/node_modules/happo-plugin-storybook/index.js:85:16)
    at ChildProcess.emit (node:events:517:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
Error: Process completed with exit code 1.
```

I tried to debug it by running that function locally, but it throws an error on this step ```execSync(`${binary} list | grep 'storybook/react@[56]'`)```.
```
[happo] Check for Storybook v6 failed. Details: Error: Command failed: npm list | grep 'storybook/react@[56]'
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at resolveBuildCommandParts (/home/spanb4/Desktop/vertex/vtx-ui-react-component-library/test.js:13:9)
    at Object.<anonymous> (/home/spanb4/Desktop/vertex/vtx-ui-react-component-library/test.js:34:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  status: 1,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 54161,
  stdout: <Buffer >,
  stderr: <Buffer >
}
```

**Comment by trotzig** [comment]
Hi @SpaNb4 and thanks for the report!

Can you try running again with a `HAPPO_DEBUG=true` environment variable set? That could give us some more useful information. 

`resolveBuildCommandParts` is definitely related, but the `execSync("${binary} list | grep 'storybook/react@[56]'")` [command is expected to fail in Storybook 7, and there's a try-catch around it](https://github.com/happo/happo-plugin-storybook/blob/16dbaad61d173cea6efc0e11055c28114ebbc86b/index.js#L37).  One theory is that you have a `build-storybook` script defined in package.json, and [it's tricking Happo that you're still on Storybook v6](https://github.com/happo/happo-plugin-storybook/blob/16dbaad61d173cea6efc0e11055c28114ebbc86b/index.js#L46). 

A quick workaround could be to define this environment variable: `HAPPO_STORYBOOK_BUILD_COMMAND="npx storybook build"`. It will [cause the automatic `resolveBuildCommandParts` check to be bypassed](https://github.com/happo/happo-plugin-storybook/blob/16dbaad61d173cea6efc0e11055c28114ebbc86b/index.js#L33).

**Comment by SpaNb4** [comment]
> Hi @SpaNb4 and thanks for the report!
> 
> Can you try running again with a `HAPPO_DEBUG=true` environment variable set? That could give us some more useful information.
> 
> `resolveBuildCommandParts` is definitely related, but the `execSync("${binary} list | grep 'storybook/react@[56]'")` [command is expected to fail in Storybook 7, and there's a try-catch around it](https://github.com/happo/happo-plugin-storybook/blob/16dbaad61d173cea6efc0e11055c28114ebbc86b/index.js#L37). One theory is that you have a `build-storybook` script defined in package.json, and [it's tricking Happo that you're still on Storybook v6](https://github.com/happo/happo-plugin-storybook/blob/16dbaad61d173cea6efc0e11055c28114ebbc86b/index.js#L46).
> 
> A quick workaround could be to define this environment variable: `HAPPO_STORYBOOK_BUILD_COMMAND="npx storybook build"`. It will [cause the automatic `resolveBuildCommandParts` check to be bypassed](https://github.com/happo/happo-plugin-storybook/blob/16dbaad61d173cea6efc0e11055c28114ebbc86b/index.js#L33).

Thank you for the lightning fast response!
Here is the output with `HAPPO_DEBUG=true`
![image](https://github.com/happo/happo-plugin-storybook/assets/69504277/b6e73355-994a-4d1f-955a-cb1149de938c)

And here's a list of the storybook scripts I have:
![image](https://github.com/happo/happo-plugin-storybook/assets/69504277/bc9ab0f1-74e3-4a00-84ed-c43cd2547207)


And now I'll try the suggested workaround

**Comment by trotzig** [comment]
Okay, since we're not seeing `Check for storybook-build command failed`, [we're incorrectly assuming it's Storybook v6 and not v7](https://github.com/happo/happo-plugin-storybook/blob/16dbaad61d173cea6efc0e11055c28114ebbc86b/index.js#L51). And then as a result, the `build-storybook` command fails. 

I'll look into making this more robust, and in the meantime you can try using `HAPPO_STORYBOOK_BUILD_COMMAND="npx storybook build"`.

**Comment by SpaNb4** [comment]
Your workaround works, thank you!

**Comment by trotzig** [comment]
I pushed v3.4.1 just now that should fix this without the need for the HAPPO_STORYBOOK_BUILD_COMMAND workaround. https://github.com/happo/happo-plugin-storybook/pull/103
