### ISSUE TITLE
Broken addons store and postmessages channel with Storybook V7

### ISSUE THREAD

**Issue by vtx-anton-chashchin** [happo/happo-plugin-storybook#104]
Recently we started to update our project to use Storybook V7 + Vite
The thing I discovered that in production storybook build addons store and postmessages channel are not working properly:
Manager page sends some postmessages to the iframe, but it doesn't handle them, because of falling back to the mockChannel
The reasons of this behavior: 
- `happo-plugin-storybook/src/addon.js` uses `@storybook/addons` which was replaced with `@storybook/manager-api` in Storybook V7
- `happo-plugin-storybook/src/decorator.js` uses `@storybook/addons` which was replaced with `@storybook/preview-api` in Storybook V7

Please see https://www.npmjs.com/package/@storybook/addons

Also I made the script which rewrites this peer deps on the post install stage and it started to work fine, so could you please release the fix for this?

**Comment by trotzig** [comment]
Hi @vtx-anton-chashchin -- thanks for the report! I'll look into this during the week. Glad to hear you have a workaround for now.
