### ISSUE TITLE
@storybook/api error

### ISSUE THREAD

**Issue by chortis** [happo/happo-plugin-storybook#133]
The preset references a deprecated package `@storybook/api` and tries to resolve it which breaks it. From here in the docs: https://docs.happo.io/docs/storybook#configuration
![image](https://github.com/user-attachments/assets/2002f666-9c4a-4758-9fc3-0764c3caed3e)

Also, there is a typo here as it says to add it in the `preview.js` file but it needs to go in `main.js`.

You can install the `@storybook/api` package to get around it but that isn't ideal as it throws an incompatibility warning.

**Comment by lencioni** [comment]
Hi Curtis, thanks for the report! I think all of the things from that package moved to `@storybook/manager-api`. I'll get a PR ready to fix this shortly.

**Comment by lencioni** [comment]
This is now published in 4.4.1. Thanks again for the report!
