### ISSUE TITLE
Possibility to have a window global callback/variable that needs to be run/set before an example is ready

### ISSUE THREAD

**Issue by jack-sf** [happo/happo-plugin-storybook#15]
In custom happo, you can have an async example by returning a promise from the function that returns the component.

There is no such possibility in storybook though. You can only do some arbitrary `delay` but this is a mediocre solution. (Delay will very often be either too long or too short.).

If I could have Happo wait until I set a variable like `window.HAPPO_READY = true` or call `window.happoExampleReady()` , then I could easily write some decorator for my stories, that i.e. waits until x happens and then calls happoExampleReady().

Usage example:

Right now a lot of our examples don't have images loaded or they are loaded partially. (Probably because happo doesn't detect some of them/doesn't wait for them, or because they appear after the component init?)

Also in a few examples we do some API request and there also, happo doesn't really wait for it, until I force it to wait some long delay like 10s.

**Comment by trotzig** [comment]
What if there was a config option that allowed you to wait for a specific selector to return some element(s). Something like 

```js
  storiesOf('Button', module)
    .add('with text', () => <Button>Hello Button</Button>, {
      happo: { waitForSelector: ".foo" },
    })
```

When it comes to images, happo should wait for them as long as they are in the dom at the time we consider an example to be "done". In your case it sounds like the `img` nodes might not be in the dom after the first render (but some other content is). This would cause happo to think it has no images to wait for.

**Comment by jack-sf** [comment]
Mhm i think waiting for selector is bad approach. In today days when people
use component frameworks like angular or react, u should use callbacks
passed to components passed as a prop instead.

**Comment by trotzig** [comment]
Yeah that is better. Although I don't fully see how that would look like in a storybook setup. Perhaps something like this

```js
  storiesOf('Some async component', module).add('default', (done) => <AsyncComponent onReady={done} />);
```

In your codebase @jack-sf, would this be possible? I fear that the "done" moment will happen quite deep down the render tree, in which passing the prop down all the way would be annoying.

**Comment by jack-sf** [comment]
Yeah, I was thinking as well, that it might happen down deep in the tree,
and we would have to extract sometimes props just for happo purposes. But I
don't know now about better solution. Maybe mix of those two. Or something
else. If u want to wait i can think of something maybe during the weekend ;P

**Comment by trotzig** [comment]
I pushed a fix that could potentially solve the issue without needing manual intervention. By hooking into xhr requests (including fetch) we can wait for some sort of "silence" before we consider a story done rendering. If you have time to try version 2.2.0-rc.1 and report back what you see (screenshots), that would be great!

**Comment by trotzig** [comment]
@jack-sf Let me know if you think this issue could be closed! While we don't yet have support for a callback, the xhr/fetch waiting might have resolved most of the issues we were trying to solve with the callback.

**Comment by jack-sf** [comment]
Yeah, thanks to waiting for images and xhr, and because we write our components in such a way that they are ready to be screenshoted immediately after initial mount, we don't need this feature for now.

It doesn't mean though that somebody else might need it in the future though ;P

**Comment by trotzig** [comment]
We can reopen this issue if we encounter a new need for the feature. 👍 

As you mentioned, getting components ready right away is important. I'll try to incorporate this in the main `happo.io` docs (which I'm working on right now).
