### ISSUE TITLE
Safari not taking full page screenshots

### ISSUE THREAD

**Issue by stefanteixeira** [happo/happo-plugin-storybook#39]
Hi! I'm evaluating Happo to run against some composed pages we have on Storybook.

I noticed that Safari is not taking full page screenshots, the screenshot dimensions are always exactly the specified viewport (e.g: 1440x900). Is there some additional configuration I could do?

**Comment by trotzig** [comment]
Hi @stefanteixeira! You can use the `scrollStitch` option for your safari target. Docs: https://docs.happo.io/docs/cypress#continuous-integration

**Comment by stefanteixeira** [comment]
@trotzig But I'm using Storybook integration, not Cypress 😕

**Comment by trotzig** [comment]
Apologies, wrong link! Should have been this: https://docs.happo.io/docs/configuration#target-scrollstitch

**Comment by stefanteixeira** [comment]
Found it now too! Thanks @trotzig :smile:
