### ISSUE TITLE
Chrome screenshots not fully loading components

### ISSUE THREAD

**Issue by stefanteixeira** [happo/happo-plugin-storybook#40]
Hey! I'm evaluating Happo to run against some composed pages we have on Storybook. My screenshots are looking good on Safari and Firefox, but on Chrome we have components/sections not loading and screenshots getting almost blank after some point.

We tried disabling lazy loading, disabling hydration, but it doesn't help. Weird is that Firefox screenshots are looking fine.

I noticed that if I set Chrome viewport with a huge height (such as `1440x10000`), everything until 10000px height renders perfectly, but this workaround is not perfect since for pages with height < 10000px the rest would be rendered blank 😕 

What could I do? A `scrollStitch` solution for Chrome would be perfect.

Some screenshots:

<details>
<summary>Screenshot 1</summary>
<img src="https://user-images.githubusercontent.com/4781037/87338001-c8fbfb00-c51a-11ea-8f81-856a0f536f57.png">
</details>
<details>
<summary>Screenshot 2</summary>
<img src="https://user-images.githubusercontent.com/4781037/87337929-a964d280-c51a-11ea-8d56-0acd4fe7b9a3.png">
</details>

**Comment by trotzig** [comment]
Hi @stefanteixeira! I'm going to have a closer look at this. [A similar issue](https://github.com/happo/happo.io/issues/167) has been reported to the happo.io library recently as well.

**Comment by trotzig** [comment]
I'm getting closer to a fix/workaround for this issue. It seems to only happen to tall pages (~10K pixels and up), and it has to do with how we're using `clip` when taking the screenshot. I hope to have a fix deployed for this tomorrow.

**Comment by stefanteixeira** [comment]
That's great news, @trotzig! When you have that, I can test right away if it solved the issue for us.

**Comment by trotzig** [comment]
The update has now been deployed to our Chrome cluster at happo.io. Let me know what you see after this update!

**Comment by stefanteixeira** [comment]
@trotzig I'm very happy to say it worked nicely! Thanks a lot!
