### ISSUE TITLE
Feature request: Ability to limit targets

### ISSUE THREAD

**Issue by DHedgecock** [happo/happo-plugin-storybook#64]
Hello, love using Happo, thanks for the amazing tool 🎉 

This issue is a request for the ability to control the targets for individual stories.

Looking at the Happo only example I see this: https://docs.happo.io/docs/examples#limiting-targets
And looking at the Happo-Cypress example I see this: https://docs.happo.io/docs/cypress#selecting-targets

We'd love to have the same ability for Storybook. The specific use case being we have a few stories where we'd like to opt-in to additional viewport size screenshots, eg:

```javascript
export const SpecialComponentStory = Template.bind({});
SpecialComponentStory.parameters = {
  happo: {
    targets: ['mobile', 'tablet', 'laptop_15', 'monitor_27'],
  },
};
```

Thanks!

**Comment by trotzig** [comment]
Hi @DHedgecock! Thanks for the feature request. I actually thought this was already in place. It makes total sense to have this be consistent across different integrations. I've started working on a PR right away.

**Comment by trotzig** [comment]
Released in https://github.com/happo/happo-plugin-storybook/releases/tag/v2.10.0

I'm going to follow up with adding docs at docs.happo.io soon. For now this is only documented in the release notes.

**Comment by DHedgecock** [comment]
Unbelievably fast response and it works like a charm! Thank you 🎉
