### ISSUE TITLE
Extend 'Limiting targets' functionality

### ISSUE THREAD

**Issue by pudek357** [happo/happo-plugin-storybook#89]
Hello 👋.

I'd try to describe our case.
Imagine you have 1k stories in the code base.

For all stories we want to generate desktop screenshots, so:

**.happo.js**
```js
module.exports = {
  targets: {
    chrome: new RemoteBrowserTarget('chrome', {
      viewport: '1024x768',
    }),
  },
  ...
}
```

But only for some of them, we want to have mobile screenshot:

**component story file**:
```tsx
export const DefaultOnMobile: ComponentStory<typeof Component> = () => (
  <Component vertical="someVariant" />
)
DefaultOnMobile.storyName = 'Default - on mobile'
DefaultOnMobile.parameters = {
  viewport: { defaultViewport: 'mobile' }, // our predefined viewport config
  happo: { targets: ['chrome-small'] }
}
```

With the current implementation of `happo-plugin-storybook` the screenshot for `DefaultOnMobile` will not be created, as `chrome-small` is not defined, but as I mentioned above, we only want to create mobile screenshots only for a few of the stories.

**Comment by trotzig** [comment]
Hi @pudek357! 

I think your best option here is to include all the available targets in `.happo.js` and then set a default for all Storybook stories to only use `chrome`. Then for individual components you can override the default to include/exclude certain targets. Like this: 

**.storybook/preview.js**
```js
// .storybook/preview.js
export const parameters = {
  happo: { targets: ['chrome'] },
};
```

**component story file:**
```js
DefaultOnMobile.parameters = {
  happo: { targets: ['chrome-small'] }
}
```

**.happo.js**
```
module.exports = {
  targets: {
    chrome: new RemoteBrowserTarget('chrome', {
      viewport: '1024x768',
    }),
    'chrome-small': new RemoteBrowserTarget('chrome', {
      viewport: '400x600',
    }),
  },
  ...
}
```

Let me know if that works for you!

**Comment by pudek357** [comment]
Hi @trotzig!
I forgot that we can export the default configuration from `.storybook/preview.js` file.

The problem is solved! 🚀
