### ISSUE TITLE
3.2.0 failing

### ISSUE THREAD

**Issue by markwoon** [happo/happo-plugin-storybook#93]
Updating from 3.1.0 to 3.2.0 fails with:

```
 > yarn happo run
No [sha] provided. A temporary one will be used in place: "dev-393ed6dc963506aea14a".
Generating static package...
error: unknown option '--output-dir'
✗
Error: Failed to build static storybook package
    at ChildProcess.<anonymous> (xxx\node_modules\happo-plugin-storybook\index.js:67:16)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

xxx\node_modules\happo-plugin-storybook\index.js:67
        reject(new Error('Failed to build static storybook package'));
               ^
Error: Failed to build static storybook package
    at ChildProcess.<anonymous> (xxx\node_modules\happo-plugin-storybook\index.js:67:16)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

We have not upgraded to Storybook 7.  Is 3.2.0 storybook 7 only?

**Comment by trotzig** [comment]
Hi @markwoon, thanks for the report!

The `--output-dir` option has been there for a while, so I'm surprised that it is unknown. 

This library is tested with Storybook [v5](https://github.com/happo/happo-plugin-storybook/blob/2aed0ff812b60c96528aca1941403b5f763eec90/.github/workflows/test.yml#L46) and [v6](https://github.com/happo/happo-plugin-storybook/blob/2aed0ff812b60c96528aca1941403b5f763eec90/.github/workflows/test.yml#L27) as well as v7. But it's possible that I screwed up something with the most recent release. 

Looking at the code, I see that we conditionally use `npx build-storybook` or `npx storybook build`: 
```js
function resolveBuildCommandParts() {
  const binary = fs.existsSync('yarn.lock') ? 'yarn' : 'npm';
  try {
    execSync(`${binary} list | grep 'storybook/react@[56]'`);
    // Storybook 6 or earlier, or the user has a custom build-storybook script
    // defined.
    return ['build-storybook'];
  } catch (e) {
    // Storybook 7 or later
    return ['storybook', 'build'];
  }
}
```
https://github.com/happo/happo-plugin-storybook/blob/2aed0ff812b60c96528aca1941403b5f763eec90/index.js#L35

I wonder if this function isn't working in your case. For instance, what's the result of running `npx list | grep 'storybook/react@[56]'` in your project?

**Comment by markwoon** [comment]
`npm ERR! could not determine executable to run`

Does it make a difference if we use yarn vs. npm?

**Comment by markwoon** [comment]
Wait, I see you're checking for yarn.  But we're using yarn 2, so `yarn list` won't work either:

```
> yarn list
Usage Error: Couldn't find a script named "list".
```

But this might work:
```
> yarn info | grep 'storybook/react@npm:[56]'
├─ @storybook/react@npm:6.5.16
│     ├─ @storybook/react@npm:6.5.16 → npm:6.5.16 [5d133]
```

**Comment by trotzig** [comment]
Good catch -- let me make a fix for that.

**Comment by trotzig** [comment]
Give v3.2.3 a try and see if that fixes the issue: 
https://github.com/happo/happo-plugin-storybook/releases/tag/v3.2.3

**Comment by markwoon** [comment]
Works now.
