### ISSUE TITLE
snapshot doesn't wait for userEvent.type with delay

### ISSUE THREAD

**Issue by Q-Man** [happo/happo-plugin-storybook#97]
Follow up observation of `userEvent` behavior after [this bug](https://github.com/happo/happo-plugin-storybook/issues/95) was fixed.

(Storybook in combination with @storybook/addon-interactions)

When `userEvent.type` is used with a delay in a `play` function the snapshot doesn't wait for the complete input. But it's working correctly when `userEvent.type` is used in `beforeSnapshot`.

I added the case to the demo repo:
https://github.com/Q-Man/happo-storybook-userevent/

Here's the code:

```jsx
import React from 'react'
import {userEvent, screen, fireEvent} from "@storybook/testing-library"

const Test = () => {
  return <div>
    <input type="radio" name="test" id="test1"/>
    <label htmlFor="test1">test1</label>
    <input type="radio" name="test" id="test2"/>
    <label htmlFor="test2">test2</label>
    <input type="text" id="test3" data-testid="test3" style={{width: '250px'}}/>
  </div>
}

const meta = {component: Test}

export const Default = {}

const play = async () => {
  await userEvent.click(screen.getByLabelText('test2'))
  await userEvent.type(screen.getByTestId('test3'), 'hello world I am a bit a longer text', {delay: 100})
}

export const WithUserEvent = {
  // incomplete snapshot, doesn't wait for complete typing
  play
}

export const WithBeforeScreenshot = {
  parameters: {
    happo: {
      // complete snapshot, works as expected
      beforeScreenshot: play,
    }
  }
}

export default meta
```

<img width="913" alt="Bildschirmfoto 2023-05-30 um 11 28 09" src="https://github.com/happo/happo-plugin-storybook/assets/53130/f18d31e0-7f82-4085-bb63-2f1a98a3023e">

**Comment by trotzig** [comment]
Can you try updating to the latest happo-plugin-storybook version and see if that helps? I found this too yesterday and I think I fixed it.

**Comment by Q-Man** [comment]
> Can you try updating to the latest happo-plugin-storybook version and see if that helps? I found this too yesterday and I think I fixed it.

It's updated, and it's happening also with the updated version.

I added another commit to the [demo repo](https://github.com/Q-Man/happo-storybook-userevent/) demonstrating it.

**Comment by trotzig** [comment]
Thanks -- turns out this is caused by a 2s timeout happening for async interactions. I'll add a way to up this timeout through config but in the meantime you can set the delay to a smaller value. As you can see in the screenshot, Happo waited for ~20 characters with 100ms delay, so a shorter delay can make them all fit before the timeout happens.

**Comment by trotzig** [comment]
If you update to v3.3.0 you can set the timeout to a value higher than the default of 2000 ms. https://github.com/happo/happo-plugin-storybook/releases/tag/v3.3.0

```js
// .storybook/preview.js
import { setRenderTimeoutMs } from 'happo-plugin-storybook/register';

setRenderTimeoutMs(5000);
```

**Comment by Q-Man** [comment]
Awesome, thank you. 🙇 🙂 

One more question about the general functionality:

Is it possible to trigger a happo snapshot in the middle of the play function, or only at the end?

To do something like this within a single play function:
- simulate a click to open a menu
- take a snapshot
- simulate a mouse-over over a menu element
- take another snapshot

**Comment by trotzig** [comment]
Hi @Q-Man -- I came back here randomly and saw that you had made a question that I hadn't answered. At the time we didn't have a way to take multiple screenshots for a story but since about a month ago, you can use `forceHappoScreenshot`. Docs here: https://docs.happo.io/docs/storybook#using-forcehapposcreenshot
